apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchlabels:
      app: mysql
  template:
    metadata:
      name: mysql-template
      labels:
        app: myapp
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin123
            - name: MYSQL_DATABASE
              value: studentapp
            - name: MYSQl_ROOT_PASSWORD
              value: root
...
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  lables:
    app:myapp
spec:
  ClusterIP: None
  selector:
    app: myapp
  ports:
    - name: myport
      protocol: TCP
      port: 3306
      targetPort: 3306