apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app:myapp
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWeiteOnce
    storageClassName: standard
    volumeMode: Filesystem
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: /mnt/data
      